/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ADMIN;

import Clases.conexion;
import java.sql.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Vanessa
 */
public class Menu_admin extends javax.swing.JFrame {

    /**
     * Creates new form Menu_admin
     */
    
    int xMouse, yMouse;
    
    conexion consultas=new conexion();
   
    public Menu_admin() {
         try {
            UIManager.setLookAndFeel(new FlatLightLaf());  // O puedes usar FlatLightLaf para el modo claro
        } catch (UnsupportedLookAndFeelException e) {
        }
         
        initComponents();   
        
        consultas.RellenarComboBox("estacionamiento", "id_estacionamiento",CB_estacionamiento);
        tiempo(); //Lama el metodo para mostrarlo
        
    }
    
    // Metodo para obener nombre de usuario 
    public void setNombreUsuario(String nombreUsuario) {
        lb_nombreUsuario.setText("Bienvenido, " + nombreUsuario);
    }
    
    // Metodo para obtener la hora y fecha actual
    public void tiempo(){
          Timer timer = new Timer(1000, e -> {
            java.util.Date date = new java.util.Date();

            SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");
            String formattedDate = dateFormatter.format(date);
            lb_fecha.setText(formattedDate);

            SimpleDateFormat timeFormatter = new SimpleDateFormat("hh:mm:ss a");
            String formattedTime = timeFormatter.format(date);
            lb_tiempo.setText(formattedTime);

            
        });
        timer.start();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JPanel();
        lb_exit = new javax.swing.JLabel();
        btn_minmax = new javax.swing.JPanel();
        lb_minmax = new javax.swing.JLabel();
        btn_min = new javax.swing.JPanel();
        lb_min = new javax.swing.JLabel();
        lb_tiempo = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        lb_nombreUsuario = new javax.swing.JLabel();
        IZQ2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_usuarios = new Clases.PanelRound();
        lb_usuarios = new javax.swing.JLabel();
        btn_Membresia = new Clases.PanelRound();
        lb_membresia = new javax.swing.JLabel();
        btn_registros = new Clases.PanelRound();
        lb_registros = new javax.swing.JLabel();
        btn_HorayFracc = new Clases.PanelRound();
        lb_HorayFraccion = new javax.swing.JLabel();
        btn_Lugares = new Clases.PanelRound();
        lb_lugares = new javax.swing.JLabel();
        btn_SalVehiculos = new Clases.PanelRound();
        lb_salidaVehiculos = new javax.swing.JLabel();
        btn_cerrarsesion = new Clases.PanelRound();
        lb_cerrarsesion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        centro = new javax.swing.JPanel();
        jp_principal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jp_usuarios = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lb_estac = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_iduser = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_curp = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        CB_estacionamiento = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btn_registrar = new Clases.PanelRound();
        lb_registrar = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_telefono = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        cmbRol1 = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jp_membresia = new javax.swing.JPanel();
        jp_registros = new javax.swing.JPanel();
        jp_HorayFraccion = new javax.swing.JPanel();
        jp_lugares = new javax.swing.JPanel();
        jp_salidaVehiculos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(175, 23, 64));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 32, 78));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 17));

        jLabel8.setFont(new java.awt.Font("Soberana Sans", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("La estación");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_exit.setBackground(new java.awt.Color(175, 23, 64));

        lb_exit.setBackground(new java.awt.Color(175, 23, 64));
        lb_exit.setFont(new java.awt.Font("Soberana Sans", 0, 14)); // NOI18N
        lb_exit.setForeground(new java.awt.Color(255, 255, 255));
        lb_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exit.setText("X");
        lb_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_exitLayout = new javax.swing.GroupLayout(btn_exit);
        btn_exit.setLayout(btn_exitLayout);
        btn_exitLayout.setHorizontalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_exitLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lb_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        btn_exitLayout.setVerticalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_minmax.setBackground(new java.awt.Color(175, 23, 64));

        lb_minmax.setBackground(new java.awt.Color(175, 23, 64));
        lb_minmax.setFont(new java.awt.Font("Soberana Sans", 0, 24)); // NOI18N
        lb_minmax.setForeground(new java.awt.Color(255, 255, 255));
        lb_minmax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_minmax.setText("/");
        lb_minmax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_minmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_minmaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_minmaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_minmaxMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_minmaxLayout = new javax.swing.GroupLayout(btn_minmax);
        btn_minmax.setLayout(btn_minmaxLayout);
        btn_minmaxLayout.setHorizontalGroup(
            btn_minmaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_minmaxLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lb_minmax, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        btn_minmaxLayout.setVerticalGroup(
            btn_minmaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_minmax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        btn_min.setBackground(new java.awt.Color(175, 23, 64));

        lb_min.setBackground(new java.awt.Color(175, 23, 64));
        lb_min.setFont(new java.awt.Font("Soberana Sans", 0, 18)); // NOI18N
        lb_min.setForeground(new java.awt.Color(255, 255, 255));
        lb_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_min.setText("-");
        lb_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_min.setFocusable(false);
        lb_min.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        lb_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_minMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_minLayout = new javax.swing.GroupLayout(btn_min);
        btn_min.setLayout(btn_minLayout);
        btn_minLayout.setHorizontalGroup(
            btn_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_minLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lb_min, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        btn_minLayout.setVerticalGroup(
            btn_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lb_tiempo.setBackground(new java.awt.Color(187, 187, 187));
        lb_tiempo.setFont(new java.awt.Font("Soberana Sans", 0, 14)); // NOI18N
        lb_tiempo.setForeground(new java.awt.Color(204, 204, 204));
        lb_tiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tiempo.setText("hh:mm:ss am");

        lb_fecha.setFont(new java.awt.Font("Soberana Sans", 0, 14)); // NOI18N
        lb_fecha.setForeground(new java.awt.Color(204, 204, 204));
        lb_fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_fecha.setText("dd/mm/yyyy");

        lb_nombreUsuario.setFont(new java.awt.Font("Louis George Cafe", 1, 12)); // NOI18N
        lb_nombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lb_nombreUsuario.setText("user");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lb_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btn_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_minmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(btn_minmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_nombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_tiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        IZQ2.setBackground(new java.awt.Color(0, 34, 77));
        IZQ2.setPreferredSize(new java.awt.Dimension(200, 502));

        jSeparator1.setBackground(new java.awt.Color(222, 124, 125));
        jSeparator1.setForeground(new java.awt.Color(222, 124, 125));

        btn_usuarios.setBackground(new java.awt.Color(0, 34, 77));
        btn_usuarios.setRoundBottomLeft(37);
        btn_usuarios.setRoundTopLeft(37);
        btn_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseExited(evt);
            }
        });

        lb_usuarios.setBackground(new java.awt.Color(255, 255, 255));
        lb_usuarios.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        lb_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_usuarios.setText("USUARIOS");
        lb_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_usuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_usuariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_usuariosLayout = new javax.swing.GroupLayout(btn_usuarios);
        btn_usuarios.setLayout(btn_usuariosLayout);
        btn_usuariosLayout.setHorizontalGroup(
            btn_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_usuariosLayout.setVerticalGroup(
            btn_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        btn_Membresia.setBackground(new java.awt.Color(0, 34, 77));
        btn_Membresia.setRoundBottomLeft(37);
        btn_Membresia.setRoundTopLeft(37);

        lb_membresia.setBackground(new java.awt.Color(187, 187, 187));
        lb_membresia.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        lb_membresia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_membresia.setText("Membresia");
        lb_membresia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_membresiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_membresiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_membresiaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_MembresiaLayout = new javax.swing.GroupLayout(btn_Membresia);
        btn_Membresia.setLayout(btn_MembresiaLayout);
        btn_MembresiaLayout.setHorizontalGroup(
            btn_MembresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_membresia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_MembresiaLayout.setVerticalGroup(
            btn_MembresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_membresia, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        btn_registros.setBackground(new java.awt.Color(0, 34, 77));
        btn_registros.setRoundBottomLeft(37);
        btn_registros.setRoundTopLeft(37);

        lb_registros.setBackground(new java.awt.Color(187, 187, 187));
        lb_registros.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        lb_registros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_registros.setText("Registros");
        lb_registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_registrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_registrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_registrosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_registrosLayout = new javax.swing.GroupLayout(btn_registros);
        btn_registros.setLayout(btn_registrosLayout);
        btn_registrosLayout.setHorizontalGroup(
            btn_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_registros, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );
        btn_registrosLayout.setVerticalGroup(
            btn_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_registros, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        btn_HorayFracc.setBackground(new java.awt.Color(0, 34, 77));
        btn_HorayFracc.setRoundBottomLeft(37);
        btn_HorayFracc.setRoundTopLeft(37);

        lb_HorayFraccion.setBackground(new java.awt.Color(187, 187, 187));
        lb_HorayFraccion.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        lb_HorayFraccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_HorayFraccion.setText("Hora y fracción");
        lb_HorayFraccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_HorayFraccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_HorayFraccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_HorayFraccionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_HorayFraccLayout = new javax.swing.GroupLayout(btn_HorayFracc);
        btn_HorayFracc.setLayout(btn_HorayFraccLayout);
        btn_HorayFraccLayout.setHorizontalGroup(
            btn_HorayFraccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_HorayFraccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_HorayFraccLayout.setVerticalGroup(
            btn_HorayFraccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_HorayFraccion, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        btn_Lugares.setBackground(new java.awt.Color(0, 34, 77));
        btn_Lugares.setRoundBottomLeft(37);
        btn_Lugares.setRoundTopLeft(37);

        lb_lugares.setBackground(new java.awt.Color(187, 187, 187));
        lb_lugares.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        lb_lugares.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_lugares.setText("Lugares");
        lb_lugares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_lugaresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_lugaresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_lugaresMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_LugaresLayout = new javax.swing.GroupLayout(btn_Lugares);
        btn_Lugares.setLayout(btn_LugaresLayout);
        btn_LugaresLayout.setHorizontalGroup(
            btn_LugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_lugares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_LugaresLayout.setVerticalGroup(
            btn_LugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_lugares, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        btn_SalVehiculos.setBackground(new java.awt.Color(0, 34, 77));
        btn_SalVehiculos.setRoundBottomLeft(37);
        btn_SalVehiculos.setRoundTopLeft(37);

        lb_salidaVehiculos.setBackground(new java.awt.Color(187, 187, 187));
        lb_salidaVehiculos.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        lb_salidaVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_salidaVehiculos.setText("Salida vehículos");
        lb_salidaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_salidaVehiculosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_salidaVehiculosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_salidaVehiculosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_SalVehiculosLayout = new javax.swing.GroupLayout(btn_SalVehiculos);
        btn_SalVehiculos.setLayout(btn_SalVehiculosLayout);
        btn_SalVehiculosLayout.setHorizontalGroup(
            btn_SalVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_salidaVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_SalVehiculosLayout.setVerticalGroup(
            btn_SalVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_salidaVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        btn_cerrarsesion.setRoundBottomLeft(37);
        btn_cerrarsesion.setRoundBottomRight(37);
        btn_cerrarsesion.setRoundTopLeft(37);
        btn_cerrarsesion.setRoundTopRight(37);

        lb_cerrarsesion.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        lb_cerrarsesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_cerrarsesion.setText("Cerrar sesión");

        javax.swing.GroupLayout btn_cerrarsesionLayout = new javax.swing.GroupLayout(btn_cerrarsesion);
        btn_cerrarsesion.setLayout(btn_cerrarsesionLayout);
        btn_cerrarsesionLayout.setHorizontalGroup(
            btn_cerrarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_cerrarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );
        btn_cerrarsesionLayout.setVerticalGroup(
            btn_cerrarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_cerrarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Louis George Cafe", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Admin");

        javax.swing.GroupLayout IZQ2Layout = new javax.swing.GroupLayout(IZQ2);
        IZQ2.setLayout(IZQ2Layout);
        IZQ2Layout.setHorizontalGroup(
            IZQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IZQ2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IZQ2Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(IZQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(IZQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_usuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Membresia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_registros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_HorayFracc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Lugares, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_SalVehiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(IZQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))))
        );
        IZQ2Layout.setVerticalGroup(
            IZQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IZQ2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Membresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_registros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_HorayFracc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Lugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SalVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btn_cerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        getContentPane().add(IZQ2, java.awt.BorderLayout.LINE_START);

        centro.setBackground(new java.awt.Color(248, 244, 236));
        centro.setLayout(new java.awt.CardLayout());

        jp_principal.setBackground(new java.awt.Color(255, 204, 255));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenido");

        javax.swing.GroupLayout jp_principalLayout = new javax.swing.GroupLayout(jp_principal);
        jp_principal.setLayout(jp_principalLayout);
        jp_principalLayout.setHorizontalGroup(
            jp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_principalLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jp_principalLayout.setVerticalGroup(
            jp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_principalLayout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        centro.add(jp_principal, "card2");

        jp_usuarios.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/agregar-usuario.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Altone Trial", 0, 18)); // NOI18N
        jLabel9.setText("Agregar usuarios");

        jLabel10.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        jLabel10.setText("Id_usuario");

        jLabel11.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        jLabel11.setText("Nombre completo");

        jLabel14.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        jLabel14.setText("Número telefónico");

        lb_estac.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        lb_estac.setText("Estacionmiento");

        jLabel19.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        jLabel19.setText("CURP");

        txt_iduser.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txt_iduser.setForeground(new java.awt.Color(102, 102, 102));
        txt_iduser.setText("Ingrese el ID de usuario");
        txt_iduser.setBorder(null);
        txt_iduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_iduserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_iduserMousePressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        jLabel20.setText("Contraseña");

        txt_nombre.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(102, 102, 102));
        txt_nombre.setText("Ingrese el nombre completo");
        txt_nombre.setBorder(null);
        txt_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_nombreMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_nombreMousePressed(evt);
            }
        });

        txt_curp.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txt_curp.setForeground(new java.awt.Color(102, 102, 102));
        txt_curp.setText("Ingrese el CURP");
        txt_curp.setBorder(null);
        txt_curp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_curpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_curpMousePressed(evt);
            }
        });
        txt_curp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_curpActionPerformed(evt);
            }
        });

        txtContraseña.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(102, 102, 102));
        txtContraseña.setText("jPasswordField1");
        txtContraseña.setBorder(null);
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseExited(evt);
            }
        });

        CB_estacionamiento.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        CB_estacionamiento.setBorder(null);
        CB_estacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_estacionamientoActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        btn_registrar.setBackground(new java.awt.Color(116, 9, 56));
        btn_registrar.setRoundBottomLeft(50);
        btn_registrar.setRoundBottomRight(50);
        btn_registrar.setRoundTopLeft(50);
        btn_registrar.setRoundTopRight(50);

        lb_registrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lb_registrar.setForeground(new java.awt.Color(255, 255, 255));
        lb_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_registrar.setText("REGISTRAR");
        lb_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_registrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_registrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_registrarLayout = new javax.swing.GroupLayout(btn_registrar);
        btn_registrar.setLayout(btn_registrarLayout);
        btn_registrarLayout.setHorizontalGroup(
            btn_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_registrarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lb_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        btn_registrarLayout.setVerticalGroup(
            btn_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        txt_telefono.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(102, 102, 102));
        txt_telefono.setText("Ingrese el número teléfonico");
        txt_telefono.setBorder(null);
        txt_telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_telefonoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_telefonoMousePressed(evt);
            }
        });
        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        cmbRol1.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        cmbRol1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));
        cmbRol1.setBorder(null);
        cmbRol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRol1ActionPerformed(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        jLabel16.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        jLabel16.setText("Rango");

        javax.swing.GroupLayout jp_usuariosLayout = new javax.swing.GroupLayout(jp_usuarios);
        jp_usuarios.setLayout(jp_usuariosLayout);
        jp_usuariosLayout.setHorizontalGroup(
            jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_usuariosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_telefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_iduser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(jp_usuariosLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))))
                    .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                        .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lb_estac)
                                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CB_estacionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator8)))
                            .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel20)
                                .addComponent(txtContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                .addComponent(txt_curp)
                                .addComponent(jLabel19)
                                .addComponent(jSeparator3)
                                .addComponent(jSeparator5)
                                .addComponent(jSeparator7)
                                .addComponent(cmbRol1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jp_usuariosLayout.setVerticalGroup(
            jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_usuariosLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_iduser, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_curp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRol1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lb_estac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CB_estacionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(126, 126, 126))
        );

        centro.add(jp_usuarios, "card3");

        jp_membresia.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jp_membresiaLayout = new javax.swing.GroupLayout(jp_membresia);
        jp_membresia.setLayout(jp_membresiaLayout);
        jp_membresiaLayout.setHorizontalGroup(
            jp_membresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        jp_membresiaLayout.setVerticalGroup(
            jp_membresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        centro.add(jp_membresia, "card4");

        jp_registros.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jp_registrosLayout = new javax.swing.GroupLayout(jp_registros);
        jp_registros.setLayout(jp_registrosLayout);
        jp_registrosLayout.setHorizontalGroup(
            jp_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        jp_registrosLayout.setVerticalGroup(
            jp_registrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        centro.add(jp_registros, "card5");

        jp_HorayFraccion.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jp_HorayFraccionLayout = new javax.swing.GroupLayout(jp_HorayFraccion);
        jp_HorayFraccion.setLayout(jp_HorayFraccionLayout);
        jp_HorayFraccionLayout.setHorizontalGroup(
            jp_HorayFraccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        jp_HorayFraccionLayout.setVerticalGroup(
            jp_HorayFraccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        centro.add(jp_HorayFraccion, "card6");

        jp_lugares.setBackground(new java.awt.Color(204, 255, 153));

        javax.swing.GroupLayout jp_lugaresLayout = new javax.swing.GroupLayout(jp_lugares);
        jp_lugares.setLayout(jp_lugaresLayout);
        jp_lugaresLayout.setHorizontalGroup(
            jp_lugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        jp_lugaresLayout.setVerticalGroup(
            jp_lugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        centro.add(jp_lugares, "card7");

        javax.swing.GroupLayout jp_salidaVehiculosLayout = new javax.swing.GroupLayout(jp_salidaVehiculos);
        jp_salidaVehiculos.setLayout(jp_salidaVehiculosLayout);
        jp_salidaVehiculosLayout.setHorizontalGroup(
            jp_salidaVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        jp_salidaVehiculosLayout.setVerticalGroup(
            jp_salidaVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        centro.add(jp_salidaVehiculos, "card8");

        getContentPane().add(centro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 // --------------------------- Configuración del boton exit ----------------------------------------------------------------------
    private void lb_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lb_exitMouseClicked

    private void lb_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseEntered
         btn_exit.setBackground(new Color(204, 43, 82)); //parecido a rojo bajito
        lb_exit.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitMouseEntered

    private void lb_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseExited
        btn_exit.setBackground(new Color(175,23,64)); //Rojo  [175,23,64]
        lb_exit.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitMouseExited

// --------------------------------------- BOTON que maximiza y minimiza la ventana ----------------------------------------------
    private boolean maximizado = false; // Bandera para controlar el estado
    private void lb_minmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minmaxMouseClicked
         if (!maximizado) {
            // Maximizar la ventana
            this.setExtendedState(MAXIMIZED_BOTH);
            maximizado = true; // Cambiar el estado
         } else {
            // Restaurar tamaño original
            this.setExtendedState(NORMAL);
            maximizado = false; // Cambiar el estado
        }
    }//GEN-LAST:event_lb_minmaxMouseClicked

    private void lb_minmaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minmaxMouseEntered
        btn_minmax.setBackground(new Color(204, 43, 82)); //parecido a rojo bajito
        lb_minmax.setForeground(Color.white);
    }//GEN-LAST:event_lb_minmaxMouseEntered

    private void lb_minmaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minmaxMouseExited
         btn_minmax.setBackground(new Color(175,23,64)); //Rojo  [175,23,64]
         lb_minmax.setForeground(Color.white);
    }//GEN-LAST:event_lb_minmaxMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed
// -------------------------------------- Configuracion para minimizar -----------------------------------------------------------------
    private void lb_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minMouseClicked
                              
         this.setState(ICONIFIED); // Minimiza el JFrame
    }//GEN-LAST:event_lb_minMouseClicked

    private void lb_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minMouseEntered
        btn_min.setBackground(new Color(204, 43, 82)); //parecido a rojo bajito
        lb_min.setForeground(Color.white);
    }//GEN-LAST:event_lb_minMouseEntered

    private void lb_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minMouseExited
         btn_min.setBackground(new Color(175,23,64)); //Rojo  [175,23,64]
         lb_min.setForeground(Color.white);
    }//GEN-LAST:event_lb_minMouseExited

    // ---------------------------------- LOGICA DEL BOTON REGISTRAR USUARIOS ---------------------------------------------
    private void lb_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_registrarMouseClicked
         // Capturar los datos de los campos de texto del formulario
        String id_usuario = txt_iduser.getText();  // txtIdUsuario es el JTextField para el id_usuario
        String nombre = txt_nombre.getText();         // txtNombre es el JTextField para el nombre
        String telefono = txt_telefono.getText();     // txtTelefono es el JTextField para el telefono
        String rol = cmbRol1.getSelectedItem().toString(); // cmbRol es el JComboBox para el rol
        String curp = txt_curp.getText();  // txtCredencial es el JTextField para las credenciales
        String estacionamiento = CB_estacionamiento.getSelectedItem().toString(); // cmbRol es el JComboBox para el rol
        String contraseña = new String(txtContraseña.getPassword()); // txtContraseña es el JPasswordField para la contraseña
        

        // Establecer la conexión
        Connection con = conexion.getConection();
        if (con != null) {
            try {
                // Crear la consulta SQL para insertar los datos
                String sql = "INSERT INTO usuario (id_usuario, Nombre, Telefono, Rango, CURP, id_estacionamiento, Contraseña) VALUES (?, ?, ?, ?, ?, ?,?)";

                // Preparar la sentencia SQL
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, id_usuario);
                ps.setString(2, nombre);
                ps.setString(3, telefono);
                ps.setString(4, rol);
                ps.setString(5, curp);
                ps.setString(6, estacionamiento);
                ps.setString(7, contraseña); // Si deseas encriptar la contraseña, aquí debes hacerlo antes de insertarla

                // Ejecutar la consulta
                int rowsAffected = ps.executeUpdate();

                // Verificar si la inserción fue exitosa
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Usuario registrado exitosamente.");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al registrar usuario.");
                }

                // Cerrar la conexión y el PreparedStatement
                ps.close();
                con.close();

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al conectar a la base de datos: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo establecer conexión con la base de datos.");
        }
    }//GEN-LAST:event_lb_registrarMouseClicked

    private void lb_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_registrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_registrarMouseEntered

    private void lb_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_registrarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_registrarMouseExited

    private void btn_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseClicked
       
    }//GEN-LAST:event_btn_usuariosMouseClicked

    private void btn_usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseEntered
        
    }//GEN-LAST:event_btn_usuariosMouseEntered

    private void btn_usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseExited
        
    }//GEN-LAST:event_btn_usuariosMouseExited

    private void CB_estacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_estacionamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_estacionamientoActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_curpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_curpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_curpActionPerformed

    private void txt_iduserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_iduserMousePressed
        if (txt_iduser.getText().equals("Ingrese el ID de usuario")) {
            txt_iduser.setText("");
            txt_iduser.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_iduserMousePressed

    private void txt_curpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_curpMousePressed
        if (txt_curp.getText().equals("Ingrese el CURP")) {
            txt_curp.setText("");
            txt_curp.setForeground(Color.black);
        }

        // Añadir un KeyListener para convertir a mayúsculas y validar la longitud del texto
        txt_curp.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                // Convertir a mayúsculas si la tecla presionada es una letra minúscula
                char c = e.getKeyChar();
                if (Character.isLowerCase(c)) {
                    // Convertir el carácter a mayúscula
                    e.setKeyChar(Character.toUpperCase(c));
                }

                // Si el texto ya tiene 18 caracteres y se intenta ingresar más, se bloquea la entrada
                if (txt_curp.getText().length() >= 18) {
                    e.consume();  // Bloquea la entrada de más caracteres
                    JOptionPane.showMessageDialog(null, "Ingreso más de los caracteres esperados (18 caracteres)", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }
        });   
    }//GEN-LAST:event_txt_curpMousePressed

    private void txt_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombreMousePressed
        if (txt_nombre.getText().equals("Ingrese el nombre completo")) {
            txt_nombre.setText("");
            txt_nombre.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_nombreMousePressed

    private void txt_telefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_telefonoMousePressed
        if (txt_telefono.getText().equals("Ingrese el número teléfonico")) {
            txt_telefono.setText("");
            txt_telefono.setForeground(Color.black);
        } 
        
        txt_telefono.addKeyListener(new KeyAdapter() { //Solo se esperan números
        @Override
        public void keyTyped(KeyEvent e) {
            // Obtener el carácter ingresado
            char c = e.getKeyChar();
            
            // Verificar si el carácter es un número o si es la tecla de retroceso 
            if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
                e.consume();  // Si no es un número, se bloquea la entrada
                JOptionPane.showMessageDialog(null, "Ingrese solo números", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
            
            if (txt_telefono.getText().length() >= 10) {
                if (Character.isDigit(c)) {
                    e.consume();  // Si el número de caracteres es 10, no se permite añadir más
                    JOptionPane.showMessageDialog(null, "El número telefónico no puede tener más de 10 dígitos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    });
    }//GEN-LAST:event_txt_telefonoMousePressed

    private void txt_iduserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_iduserMouseExited
        if (txt_iduser.getText().isEmpty()) {
            txt_iduser.setText("Ingrese el ID de usuario");
            txt_iduser.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_txt_iduserMouseExited

    private void txt_curpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_curpMouseExited
        if (txt_curp.getText().isEmpty()) {
            txt_curp.setText("Ingrese el CURP");
            txt_curp.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_txt_curpMouseExited

    private void txt_nombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombreMouseExited
        if (txt_nombre.getText().isEmpty()) {
            txt_nombre.setText("Ingrese el nombre completo");
            txt_nombre.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_txt_nombreMouseExited

    private void txt_telefonoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_telefonoMouseExited
        if (txt_telefono.getText().isEmpty()) {
            txt_telefono.setText("Ingrese el número teléfonico");
            txt_telefono.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_txt_telefonoMouseExited

    private void txtContraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseExited
        if (String.valueOf(txtContraseña.getPassword()).isEmpty()) {
            txtContraseña.setText("**************");
            txtContraseña.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_txtContraseñaMouseExited

    
    // ------------------------------- LOGICA DE QUE PANEL ESTA SELECCIONADO ----------------------------------------------------------------------------
    // Variables de selección
        private String panelSeleccionado = ""; // Nombre del panel actualmente seleccionado

        private void seleccionarPanel(String panel) {
            // Restaurar colores de todos los botones y etiquetas
            restaurarEstadoPaneles();

            // Cambiar colores y mostrar el panel correspondiente
            switch (panel) {
                case "usuarios":
                    btn_usuarios.setBackground(Color.WHITE); // Seleccionado
                    lb_usuarios.setForeground(new Color(0, 34, 77)); // Fuente
                    jp_usuarios.setVisible(true);
                    break;
                case "membresia":
                    btn_Membresia.setBackground(Color.WHITE);
                    lb_membresia.setForeground(new Color(0, 34, 77));
                    jp_membresia.setVisible(true);
                    break;
                case "registros":
                    btn_registros.setBackground(Color.WHITE);
                    lb_registros.setForeground(new Color(0, 34, 77));
                    jp_registros.setVisible(true);
                    break;
                 case "HorayFraccion":
                    btn_HorayFracc.setBackground(Color.WHITE);
                    lb_HorayFraccion.setForeground(new Color(0, 34, 77));
                    jp_HorayFraccion.setVisible(true);
                    break;
                 case "Lugares":
                    btn_Lugares.setBackground(Color.WHITE);
                    lb_lugares.setForeground(new Color(0, 34, 77));
                    jp_lugares.setVisible(true);
                    break;
                 case "SalidaVehiculos":
                    btn_SalVehiculos.setBackground(Color.WHITE);
                    lb_salidaVehiculos.setForeground(new Color(0, 34, 77));
                    jp_salidaVehiculos.setVisible(true);
                    break;
                
            }

            // Actualizar el panel seleccionado
            panelSeleccionado = panel;
        }
    
        private void restaurarEstadoPaneles() {
            // Restaurar colores de todos los botones y etiquetas
            btn_usuarios.setBackground(new Color(0, 34, 77));
            lb_usuarios.setForeground(new Color(187, 187, 187));

            btn_Membresia.setBackground(new Color(0, 34, 77));
            lb_membresia.setForeground(new Color(187, 187, 187));

            btn_registros.setBackground(new Color(0, 34, 77));
            lb_registros.setForeground(new Color(187, 187, 187));
            
            btn_HorayFracc.setBackground(new Color(0, 34, 77));
            lb_HorayFraccion.setForeground(new Color(187, 187, 187));
            
            btn_Lugares.setBackground(new Color(0, 34, 77));
            lb_lugares.setForeground(new Color(187, 187, 187));
            
            btn_SalVehiculos.setBackground(new Color(0, 34, 77));
            lb_salidaVehiculos.setForeground(new Color(187, 187, 187));

            // Ocultar todos los paneles
            jp_principal.setVisible(false);
            jp_usuarios.setVisible(false);
            jp_membresia.setVisible(false);
            jp_registros.setVisible(false);
            jp_HorayFraccion.setVisible(false);
            jp_lugares.setVisible(false);
            jp_salidaVehiculos.setVisible(false);
            
        }
  
    private void lb_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_usuariosMouseClicked
        if (!panelSeleccionado.equals("usuarios")) {
            seleccionarPanel("usuarios");
        }
        
    }//GEN-LAST:event_lb_usuariosMouseClicked

    private void lb_membresiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_membresiaMouseClicked
       if (!panelSeleccionado.equals("membresia")) {
            seleccionarPanel("membresia");
        }
    }//GEN-LAST:event_lb_membresiaMouseClicked

    private void lb_usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_usuariosMouseEntered
        // Cambiar color solo si no está seleccionado
        if (!panelSeleccionado.equals("usuarios")) {
             btn_usuarios.setBackground(Color.WHITE);
            lb_usuarios.setForeground(new Color(0, 34, 77));
        }
    }//GEN-LAST:event_lb_usuariosMouseEntered

    private void lb_usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_usuariosMouseExited
        // Restaurar color solo si no está seleccionado
        if (!panelSeleccionado.equals("usuarios")) {
            btn_usuarios.setBackground(new Color(0, 34, 77));
            lb_usuarios.setForeground(new Color(187, 187, 187)); 
        }
    }//GEN-LAST:event_lb_usuariosMouseExited

    private void lb_registrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_registrosMouseClicked
        if (!panelSeleccionado.equals("registros")) {
            seleccionarPanel("registros");
        }
    }//GEN-LAST:event_lb_registrosMouseClicked

    private void lb_HorayFraccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_HorayFraccionMouseClicked
        if (!panelSeleccionado.equals("HorayFraccion")) {
            seleccionarPanel("HorayFraccion");
        }
    }//GEN-LAST:event_lb_HorayFraccionMouseClicked

    private void lb_lugaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lugaresMouseClicked
        if (!panelSeleccionado.equals("Lugares")) {
            seleccionarPanel("Lugares");
        }
    }//GEN-LAST:event_lb_lugaresMouseClicked

    private void lb_salidaVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_salidaVehiculosMouseClicked
        if (!panelSeleccionado.equals("SalidaVehiculos")) {
            seleccionarPanel("SalidaVehiculos");
        }
    }//GEN-LAST:event_lb_salidaVehiculosMouseClicked

    private void lb_membresiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_membresiaMouseEntered
        if (!panelSeleccionado.equals("membresia")) {
             btn_Membresia.setBackground(Color.WHITE);
            lb_membresia.setForeground(new Color(0, 34, 77));
        }
    }//GEN-LAST:event_lb_membresiaMouseEntered

    private void lb_registrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_registrosMouseEntered
        if (!panelSeleccionado.equals("registros")) {
             btn_registros.setBackground(Color.WHITE);
            lb_registros.setForeground(new Color(0, 34, 77));
        }
    }//GEN-LAST:event_lb_registrosMouseEntered

    private void lb_HorayFraccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_HorayFraccionMouseEntered
        if (!panelSeleccionado.equals("HorayFraccion")) {
             btn_HorayFracc.setBackground(Color.WHITE);
            lb_HorayFraccion.setForeground(new Color(0, 34, 77));
        }
    }//GEN-LAST:event_lb_HorayFraccionMouseEntered

    private void lb_lugaresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lugaresMouseEntered
        if (!panelSeleccionado.equals("Lugares")) {
             btn_Lugares.setBackground(Color.WHITE);
            lb_lugares.setForeground(new Color(0, 34, 77));
        }
    }//GEN-LAST:event_lb_lugaresMouseEntered

    private void lb_salidaVehiculosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_salidaVehiculosMouseEntered
        if (!panelSeleccionado.equals("SalidaVehiculos")) {
             btn_SalVehiculos.setBackground(Color.WHITE);
            lb_salidaVehiculos.setForeground(new Color(0, 34, 77));
        }
    }//GEN-LAST:event_lb_salidaVehiculosMouseEntered

    private void lb_membresiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_membresiaMouseExited
        if (!panelSeleccionado.equals("membresia")) {
            btn_Membresia.setBackground(new Color(0, 34, 77));
            lb_membresia.setForeground(new Color(187, 187, 187)); 
        }
    }//GEN-LAST:event_lb_membresiaMouseExited

    private void lb_registrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_registrosMouseExited
        if (!panelSeleccionado.equals("registros")) {
            btn_registros.setBackground(new Color(0, 34, 77));
            lb_registros.setForeground(new Color(187, 187, 187)); 
        }
    }//GEN-LAST:event_lb_registrosMouseExited

    private void lb_HorayFraccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_HorayFraccionMouseExited
        if (!panelSeleccionado.equals("HorayFraccion")) {
            btn_HorayFracc.setBackground(new Color(0, 34, 77));
            lb_HorayFraccion.setForeground(new Color(187, 187, 187)); 
        }
    }//GEN-LAST:event_lb_HorayFraccionMouseExited

    private void lb_lugaresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_lugaresMouseExited
        if (!panelSeleccionado.equals("Lugares")) {
            btn_Lugares.setBackground(new Color(0, 34, 77));
            lb_lugares.setForeground(new Color(187, 187, 187)); 
        }
    }//GEN-LAST:event_lb_lugaresMouseExited

    private void lb_salidaVehiculosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_salidaVehiculosMouseExited
        if (!panelSeleccionado.equals("SalidaVehiculos")) {
            btn_SalVehiculos.setBackground(new Color(0, 34, 77));
            lb_salidaVehiculos.setForeground(new Color(187, 187, 187)); 
        }
    }//GEN-LAST:event_lb_salidaVehiculosMouseExited

    private void cmbRol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRol1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRol1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SwingUtilities.invokeLater(() -> new Menu_admin().setVisible(true));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_estacionamiento;
    private javax.swing.JPanel IZQ2;
    private Clases.PanelRound btn_HorayFracc;
    private Clases.PanelRound btn_Lugares;
    private Clases.PanelRound btn_Membresia;
    private Clases.PanelRound btn_SalVehiculos;
    private Clases.PanelRound btn_cerrarsesion;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JPanel btn_min;
    private javax.swing.JPanel btn_minmax;
    private Clases.PanelRound btn_registrar;
    private Clases.PanelRound btn_registros;
    private Clases.PanelRound btn_usuarios;
    private javax.swing.JPanel centro;
    private javax.swing.JComboBox<String> cmbRol1;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel jp_HorayFraccion;
    private javax.swing.JPanel jp_lugares;
    private javax.swing.JPanel jp_membresia;
    private javax.swing.JPanel jp_principal;
    private javax.swing.JPanel jp_registros;
    private javax.swing.JPanel jp_salidaVehiculos;
    private javax.swing.JPanel jp_usuarios;
    private javax.swing.JLabel lb_HorayFraccion;
    private javax.swing.JLabel lb_cerrarsesion;
    private javax.swing.JLabel lb_estac;
    private javax.swing.JLabel lb_exit;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_lugares;
    private javax.swing.JLabel lb_membresia;
    private javax.swing.JLabel lb_min;
    private javax.swing.JLabel lb_minmax;
    private javax.swing.JLabel lb_nombreUsuario;
    private javax.swing.JLabel lb_registrar;
    private javax.swing.JLabel lb_registros;
    private javax.swing.JLabel lb_salidaVehiculos;
    private javax.swing.JLabel lb_tiempo;
    private javax.swing.JLabel lb_usuarios;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txt_curp;
    private javax.swing.JTextField txt_iduser;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
