/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ADMIN;

import Clases.conexion;
import java.sql.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Vanessa
 */
public class Menu_admin extends javax.swing.JFrame {

    /**
     * Creates new form Menu_admin
     */
    
    int xMouse, yMouse;
    public Menu_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JPanel();
        lb_exit = new javax.swing.JLabel();
        btn_minmax = new javax.swing.JPanel();
        lb_minmax = new javax.swing.JLabel();
        btn_min = new javax.swing.JPanel();
        lb_min = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        IZQ2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btn_Membresia = new Clases.PanelRound();
        jLabel21 = new javax.swing.JLabel();
        btn_DatosMembresia = new Clases.PanelRound();
        jLabel22 = new javax.swing.JLabel();
        btn_HorayFracc = new Clases.PanelRound();
        jLabel24 = new javax.swing.JLabel();
        btn_Lugares = new Clases.PanelRound();
        jLabel29 = new javax.swing.JLabel();
        btn_SalVehiculos = new Clases.PanelRound();
        jLabel30 = new javax.swing.JLabel();
        btn_Usuarios = new Clases.PanelRound();
        lbl_Usuarios = new javax.swing.JLabel();
        btn_SalVehiculos1 = new Clases.PanelRound();
        jLabel31 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        centro = new javax.swing.JPanel();
        jp_m = new javax.swing.JPanel();
        jp_usuarios = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_iduser = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_credencial = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        cmbRol = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btn_registrar = new Clases.PanelRound();
        lb_registrar = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_telefono = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jp_dm = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(175, 23, 64));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 32, 78));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 17));

        jLabel8.setFont(new java.awt.Font("Soberana Sans", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("La estación");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_exit.setBackground(new java.awt.Color(175, 23, 64));

        lb_exit.setBackground(new java.awt.Color(175, 23, 64));
        lb_exit.setFont(new java.awt.Font("Soberana Sans", 0, 14)); // NOI18N
        lb_exit.setForeground(new java.awt.Color(255, 255, 255));
        lb_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exit.setText("X");
        lb_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_exitLayout = new javax.swing.GroupLayout(btn_exit);
        btn_exit.setLayout(btn_exitLayout);
        btn_exitLayout.setHorizontalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        btn_exitLayout.setVerticalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_minmax.setBackground(new java.awt.Color(175, 23, 64));

        lb_minmax.setBackground(new java.awt.Color(175, 23, 64));
        lb_minmax.setFont(new java.awt.Font("Soberana Sans", 0, 24)); // NOI18N
        lb_minmax.setForeground(new java.awt.Color(255, 255, 255));
        lb_minmax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_minmax.setText("/");
        lb_minmax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_minmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_minmaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_minmaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_minmaxMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_minmaxLayout = new javax.swing.GroupLayout(btn_minmax);
        btn_minmax.setLayout(btn_minmaxLayout);
        btn_minmaxLayout.setHorizontalGroup(
            btn_minmaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_minmaxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_minmax, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        btn_minmaxLayout.setVerticalGroup(
            btn_minmaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_minmax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_min.setBackground(new java.awt.Color(175, 23, 64));

        lb_min.setBackground(new java.awt.Color(175, 23, 64));
        lb_min.setFont(new java.awt.Font("Soberana Sans", 0, 18)); // NOI18N
        lb_min.setForeground(new java.awt.Color(255, 255, 255));
        lb_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_min.setText("-");
        lb_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_min.setFocusable(false);
        lb_min.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        lb_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_minMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_minLayout = new javax.swing.GroupLayout(btn_min);
        btn_min.setLayout(btn_minLayout);
        btn_minLayout.setHorizontalGroup(
            btn_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_minLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_min, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        btn_minLayout.setVerticalGroup(
            btn_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Soberana Sans", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("hh:mm:ss am");

        jLabel13.setFont(new java.awt.Font("Soberana Sans", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("dd/mm/yyyy");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_minmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(btn_minmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        IZQ2.setBackground(new java.awt.Color(0, 34, 77));
        IZQ2.setPreferredSize(new java.awt.Dimension(200, 502));

        jSeparator1.setBackground(new java.awt.Color(222, 124, 125));
        jSeparator1.setForeground(new java.awt.Color(222, 124, 125));

        jLabel1.setFont(new java.awt.Font("Louis George Cafe", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");

        btn_Membresia.setRoundBottomLeft(37);
        btn_Membresia.setRoundTopLeft(37);

        jLabel21.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Membresia");

        javax.swing.GroupLayout btn_MembresiaLayout = new javax.swing.GroupLayout(btn_Membresia);
        btn_Membresia.setLayout(btn_MembresiaLayout);
        btn_MembresiaLayout.setHorizontalGroup(
            btn_MembresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_MembresiaLayout.setVerticalGroup(
            btn_MembresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_MembresiaLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(15, 15, 15))
        );

        btn_DatosMembresia.setRoundBottomLeft(37);
        btn_DatosMembresia.setRoundTopLeft(37);

        jLabel22.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Datos membresia");

        javax.swing.GroupLayout btn_DatosMembresiaLayout = new javax.swing.GroupLayout(btn_DatosMembresia);
        btn_DatosMembresia.setLayout(btn_DatosMembresiaLayout);
        btn_DatosMembresiaLayout.setHorizontalGroup(
            btn_DatosMembresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );
        btn_DatosMembresiaLayout.setVerticalGroup(
            btn_DatosMembresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_DatosMembresiaLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(15, 15, 15))
        );

        btn_HorayFracc.setRoundBottomLeft(37);
        btn_HorayFracc.setRoundTopLeft(37);

        jLabel24.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Hora y fracción");

        javax.swing.GroupLayout btn_HorayFraccLayout = new javax.swing.GroupLayout(btn_HorayFracc);
        btn_HorayFracc.setLayout(btn_HorayFraccLayout);
        btn_HorayFraccLayout.setHorizontalGroup(
            btn_HorayFraccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_HorayFraccLayout.setVerticalGroup(
            btn_HorayFraccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_HorayFraccLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(15, 15, 15))
        );

        btn_Lugares.setRoundBottomLeft(37);
        btn_Lugares.setRoundTopLeft(37);

        jLabel29.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Lugares");

        javax.swing.GroupLayout btn_LugaresLayout = new javax.swing.GroupLayout(btn_Lugares);
        btn_Lugares.setLayout(btn_LugaresLayout);
        btn_LugaresLayout.setHorizontalGroup(
            btn_LugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_LugaresLayout.setVerticalGroup(
            btn_LugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_LugaresLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(15, 15, 15))
        );

        btn_SalVehiculos.setRoundBottomLeft(37);
        btn_SalVehiculos.setRoundTopLeft(37);

        jLabel30.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Salida vehículos");

        javax.swing.GroupLayout btn_SalVehiculosLayout = new javax.swing.GroupLayout(btn_SalVehiculos);
        btn_SalVehiculos.setLayout(btn_SalVehiculosLayout);
        btn_SalVehiculosLayout.setHorizontalGroup(
            btn_SalVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_SalVehiculosLayout.setVerticalGroup(
            btn_SalVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_SalVehiculosLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(15, 15, 15))
        );

        btn_Usuarios.setRoundBottomLeft(37);
        btn_Usuarios.setRoundTopLeft(37);
        btn_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_UsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_UsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_UsuariosMouseExited(evt);
            }
        });

        lbl_Usuarios.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        lbl_Usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Usuarios.setText("USUARIOS");

        javax.swing.GroupLayout btn_UsuariosLayout = new javax.swing.GroupLayout(btn_Usuarios);
        btn_Usuarios.setLayout(btn_UsuariosLayout);
        btn_UsuariosLayout.setHorizontalGroup(
            btn_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_UsuariosLayout.setVerticalGroup(
            btn_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_UsuariosLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lbl_Usuarios)
                .addGap(17, 17, 17))
        );

        btn_SalVehiculos1.setRoundBottomLeft(37);
        btn_SalVehiculos1.setRoundTopLeft(37);

        jLabel31.setFont(new java.awt.Font("Altone Trial", 0, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Cerrar sesión");

        javax.swing.GroupLayout btn_SalVehiculos1Layout = new javax.swing.GroupLayout(btn_SalVehiculos1);
        btn_SalVehiculos1.setLayout(btn_SalVehiculos1Layout);
        btn_SalVehiculos1Layout.setHorizontalGroup(
            btn_SalVehiculos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_SalVehiculos1Layout.setVerticalGroup(
            btn_SalVehiculos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_SalVehiculos1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(15, 15, 15))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo.png"))); // NOI18N

        javax.swing.GroupLayout IZQ2Layout = new javax.swing.GroupLayout(IZQ2);
        IZQ2.setLayout(IZQ2Layout);
        IZQ2Layout.setHorizontalGroup(
            IZQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IZQ2Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(IZQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Membresia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_DatosMembresia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_HorayFracc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Lugares, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_SalVehiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(IZQ2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IZQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_SalVehiculos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IZQ2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(IZQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addGap(27, 27, 27))))
            .addGroup(IZQ2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        IZQ2Layout.setVerticalGroup(
            IZQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IZQ2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_Membresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_DatosMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_HorayFracc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Lugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SalVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btn_SalVehiculos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(IZQ2, java.awt.BorderLayout.LINE_START);

        centro.setBackground(new java.awt.Color(248, 244, 236));
        centro.setLayout(new javax.swing.OverlayLayout(centro));

        jp_m.setBackground(new java.awt.Color(204, 153, 255));

        jp_usuarios.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/agregar-usuario.png"))); // NOI18N

        jLabel9.setText("Usuarios");

        jLabel10.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        jLabel10.setText("Id_usuario");

        jLabel11.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        jLabel11.setText("Nombre completo");

        jLabel14.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        jLabel14.setText("Teléfono");

        jLabel15.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        jLabel15.setText("Rango");

        jLabel19.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        jLabel19.setText("Credencial");

        txt_iduser.setText("jTextField1");
        txt_iduser.setBorder(null);

        jLabel20.setFont(new java.awt.Font("Louis George Cafe", 0, 16)); // NOI18N
        jLabel20.setText("Contraseña");

        txt_nombre.setText("jTextField2");
        txt_nombre.setBorder(null);

        txt_credencial.setText("jTextField5");
        txt_credencial.setBorder(null);

        txtContraseña.setText("jPasswordField1");
        txtContraseña.setBorder(null);

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));
        cmbRol.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        btn_registrar.setBackground(new java.awt.Color(116, 9, 56));
        btn_registrar.setRoundBottomLeft(50);
        btn_registrar.setRoundBottomRight(50);
        btn_registrar.setRoundTopLeft(50);
        btn_registrar.setRoundTopRight(50);

        lb_registrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lb_registrar.setForeground(new java.awt.Color(255, 255, 255));
        lb_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_registrar.setText("REGISTRAR");
        lb_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_registrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_registrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_registrarLayout = new javax.swing.GroupLayout(btn_registrar);
        btn_registrar.setLayout(btn_registrarLayout);
        btn_registrarLayout.setHorizontalGroup(
            btn_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_registrarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lb_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        btn_registrarLayout.setVerticalGroup(
            btn_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        txt_telefono.setText("jTextField4");
        txt_telefono.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jp_usuariosLayout = new javax.swing.GroupLayout(jp_usuarios);
        jp_usuarios.setLayout(jp_usuariosLayout);
        jp_usuariosLayout.setHorizontalGroup(
            jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_usuariosLayout.createSequentialGroup()
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                        .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_usuariosLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_telefono, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_iduser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))))
                            .addGroup(jp_usuariosLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addGap(74, 74, 74)
                        .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(txt_credencial)
                            .addComponent(jLabel19)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator5)
                            .addComponent(jLabel15)
                            .addComponent(jSeparator7)
                            .addComponent(cmbRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        jp_usuariosLayout.setVerticalGroup(
            jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_usuariosLayout.createSequentialGroup()
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_usuariosLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel9)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_usuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_iduser, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_credencial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_telefono)
                    .addComponent(cmbRol, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(jp_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );

        javax.swing.GroupLayout jp_mLayout = new javax.swing.GroupLayout(jp_m);
        jp_m.setLayout(jp_mLayout);
        jp_mLayout.setHorizontalGroup(
            jp_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_mLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jp_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jp_mLayout.setVerticalGroup(
            jp_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        centro.add(jp_m);

        jp_dm.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jp_dmLayout = new javax.swing.GroupLayout(jp_dm);
        jp_dm.setLayout(jp_dmLayout);
        jp_dmLayout.setHorizontalGroup(
            jp_dmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        jp_dmLayout.setVerticalGroup(
            jp_dmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        centro.add(jp_dm);

        getContentPane().add(centro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 // --------------------------- Configuración del boton exit ----------------------------------------------------------------------
    private void lb_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lb_exitMouseClicked

    private void lb_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseEntered
         btn_exit.setBackground(new Color(116, 9,56)); //parecido a rojo bajito
        lb_exit.setForeground(Color.gray);
    }//GEN-LAST:event_lb_exitMouseEntered

    private void lb_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseExited
        btn_exit.setBackground(new Color(204, 43, 82)); //Rojo  [204,43,82]
        lb_exit.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitMouseExited

// --------------------------------------- BOTON que maximiza y minimiza la ventana ----------------------------------------------
    private boolean maximizado = false; // Bandera para controlar el estado
    private void lb_minmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minmaxMouseClicked
         if (!maximizado) {
            // Maximizar la ventana
            this.setExtendedState(MAXIMIZED_BOTH);
            maximizado = true; // Cambiar el estado
         } else {
            // Restaurar tamaño original
            this.setExtendedState(NORMAL);
            maximizado = false; // Cambiar el estado
        }
    }//GEN-LAST:event_lb_minmaxMouseClicked

    private void lb_minmaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minmaxMouseEntered
        btn_minmax.setBackground(new Color(116, 9,56)); //parecido a rojo bajito
        lb_minmax.setForeground(Color.gray);
    }//GEN-LAST:event_lb_minmaxMouseEntered

    private void lb_minmaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minmaxMouseExited
         btn_minmax.setBackground(new Color(204, 43, 82)); //Rojo  [204,43,82]
         lb_minmax.setForeground(Color.white);
    }//GEN-LAST:event_lb_minmaxMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed
// -------------------------------------- Configuracion para minimizar -----------------------------------------------------------------
    private void lb_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minMouseClicked
                              
         this.setState(ICONIFIED); // Minimiza el JFrame
    }//GEN-LAST:event_lb_minMouseClicked

    private void lb_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minMouseEntered
        btn_min.setBackground(new Color(116, 9,56)); //parecido a rojo bajito
        lb_min.setForeground(Color.gray);
    }//GEN-LAST:event_lb_minMouseEntered

    private void lb_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_minMouseExited
         btn_min.setBackground(new Color(204, 43, 82)); //Rojo  [204,43,82]
         lb_min.setForeground(Color.white);
    }//GEN-LAST:event_lb_minMouseExited

    private void lb_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_registrarMouseClicked
         // Capturar los datos de los campos de texto del formulario
        String id_usuario = txt_iduser.getText();  // txtIdUsuario es el JTextField para el id_usuario
        String nombre = txt_nombre.getText();         // txtNombre es el JTextField para el nombre
        String telefono = txt_telefono.getText();     // txtTelefono es el JTextField para el telefono
        String rol = cmbRol.getSelectedItem().toString(); // cmbRol es el JComboBox para el rol
        String credencial = txt_credencial.getText();  // txtCredencial es el JTextField para las credenciales
        String contraseña = new String(txtContraseña.getPassword()); // txtContraseña es el JPasswordField para la contraseña

        // Establecer la conexión
        Connection con = conexion.getConection();
        if (con != null) {
            try {
                // Crear la consulta SQL para insertar los datos
                String sql = "INSERT INTO usuario (id_usuario, nombre, telefono, rol, credencial, contraseña) VALUES (?, ?, ?, ?, ?, ?)";

                // Preparar la sentencia SQL
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, id_usuario);
                ps.setString(2, nombre);
                ps.setString(3, telefono);
                ps.setString(4, rol);
                ps.setString(5, credencial);
                ps.setString(6, contraseña); // Si deseas encriptar la contraseña, aquí debes hacerlo antes de insertarla

                // Ejecutar la consulta
                int rowsAffected = ps.executeUpdate();

                // Verificar si la inserción fue exitosa
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Usuario registrado exitosamente.");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al registrar usuario.");
                }

                // Cerrar la conexión y el PreparedStatement
                ps.close();
                con.close();

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al conectar a la base de datos: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo establecer conexión con la base de datos.");
        }
    }//GEN-LAST:event_lb_registrarMouseClicked

    private void lb_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_registrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_registrarMouseEntered

    private void lb_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_registrarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_registrarMouseExited

    private void btn_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UsuariosMouseClicked
        jp_usuarios.setVisible(true);
        jp_m.setVisible(false);
        jp_dm.setVisible(false);
    }//GEN-LAST:event_btn_UsuariosMouseClicked

    private void btn_UsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UsuariosMouseEntered
        btn_Usuarios.setBackground(new Color(255, 32, 78)); //rgb(255, 32, 78)
        lbl_Usuarios.setForeground(Color.gray);
    }//GEN-LAST:event_btn_UsuariosMouseEntered

    private void btn_UsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UsuariosMouseExited
        btn_Usuarios.setBackground(new Color(0, 34, 77)); //rgb(0, 34, 77)
        lbl_Usuarios.setForeground(Color.white);
    }//GEN-LAST:event_btn_UsuariosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IZQ2;
    private Clases.PanelRound btn_DatosMembresia;
    private Clases.PanelRound btn_HorayFracc;
    private Clases.PanelRound btn_Lugares;
    private Clases.PanelRound btn_Membresia;
    private Clases.PanelRound btn_SalVehiculos;
    private Clases.PanelRound btn_SalVehiculos1;
    private Clases.PanelRound btn_Usuarios;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JPanel btn_min;
    private javax.swing.JPanel btn_minmax;
    private Clases.PanelRound btn_registrar;
    private javax.swing.JPanel centro;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel jp_dm;
    private javax.swing.JPanel jp_m;
    private javax.swing.JPanel jp_usuarios;
    private javax.swing.JLabel lb_exit;
    private javax.swing.JLabel lb_min;
    private javax.swing.JLabel lb_minmax;
    private javax.swing.JLabel lb_registrar;
    private javax.swing.JLabel lbl_Usuarios;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txt_credencial;
    private javax.swing.JTextField txt_iduser;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
